---
########################################################################################################################
#
# Create Subnets
# Documentation: https://docs.ansible.com/ansible/latest/modules/ec2_vpc_subnet_module.html
#
########################################################################################################################

      - name: create subnet 1
        ec2_vpc_subnet:
          state: present
          az: "eu-west-1a"
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.10.1.16/28
          tags:
            family: "{{ ec2_name_prefix }}"
          resource_tags:
            Name: "{{ ec2_name_prefix }}-vpc-subnet-1"
          region: "{{ ec2_region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        register: subnet1

      - name: Checking subnet id
        debug:
          msg: "{{ subnet1.subnet.id }}"

      - name: create subnet 2
        ec2_vpc_subnet:
          state: present
          az: "eu-west-1b"
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.10.2.16/28
          tags:
            family: "{{ ec2_name_prefix }}"
          resource_tags:
            Name: "{{ ec2_name_prefix }}-vpc-subnet-2"
          region: "{{ ec2_region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        register: subnet2

      - name: Checking subnet id
        debug:
          msg: "{{ subnet2.subnet.id }}"

      - name: create subnet 3
        ec2_vpc_subnet:
          state: present
          az: "eu-west-1c"
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.10.3.16/28
          tags:
            family: "{{ ec2_name_prefix }}"
          resource_tags:
            Name: "{{ ec2_name_prefix }}-vpc-subnet-3"
          region: "{{ ec2_region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        register: subnet3

      - name: Checking subnet id
        debug:
          msg: "{{ subnet3.subnet.id }}"