---
########################################################################################################################
#
# Create Subnets
# Documentation: https://docs.ansible.com/ansible/latest/modules/ec2_vpc_subnet_module.html
#
########################################################################################################################

      - name: present subnet {{ ec2_vpc_subnets.a.name }}
        ec2_vpc_subnet:
          state: present
          az: "{{ item.az }}"
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: "{{ item.cidr }}"
          tags:
            family: "{{ ec2_name_prefix }}"
          region: "{{ ec2_region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        register: "subnets"
        loop:
          - { id: 1, az: "{{ ec2_vpc_subnets.a.name }}", cidr: '{{ ec2_vpc_subnets.a.cidr }}' }
          - { id: 2, az: "{{ ec2_vpc_subnets.b.name }}", cidr: '{{ ec2_vpc_subnets.b.cidr }}' }
          - { id: 3, az: "{{ ec2_vpc_subnets.c.name }}", cidr: '{{ ec2_vpc_subnets.c.cidr }}' }
