---
########################################################################################################################
#
# Join consul agents
# Documentation: https://www.consul.io/docs/commands/join.html
#
########################################################################################################################

    - name: "join local cluster"
      command: "consul join {{ hostvars['consul_master']['ip'] }}"
