---

- name: deploy consul
  hosts: 127.0.0.1
  connection: local
  vars:
    ec2_name_prefix: foo-bar-consul
    ec2_region: eu-west-1

  pre_tasks:
    - pause:
        prompt: "AWS ACCESS KEY required, please open README to store encrypted"
      register: aws_access_key_prompt
      no_log: yes
      when: aws_access_key is not defined

    - pause:
        prompt: "AWS SECRET KEY, please open README to store encrypted"
      register: aws_secret_key_prompt
      no_log: yes
      when: aws_secret_key is not defined

  roles:
   - { role: aws/cluster, tags: [ 'aws/cluster' ]}