---

- name: deploy consul
  hosts: 127.0.0.1
  connection: local

  pre_tasks:

    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7 to support tagging on AWS Fargate"

    - name: map environment variables
      debug: msg="{{ lookup('env','AWS_ACCESS_KEY') }}"
      vars:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        consul_key: "{{ lookup('env', 'CONSUL_KEY') }}"
      when: aws_access_key is not defined

    - name: get AWS Key
      pause:
        prompt: "AWS ACCESS KEY required, please open README to store encrypted"
      register: aws_access_key_prompt
      no_log: yes
      when: aws_access_key is not defined

    - name: set key
      set_fact:
        aws_access_key: "{{ aws_access_key_prompt.user_input }}"
      when: aws_access_key is not defined

    - name: get AWS Secret
      pause:
        prompt: "AWS SECRET KEY, please open README to store encrypted"
      register: aws_secret_key_prompt
      no_log: yes
      when: aws_secret_key is not defined

    - name: set secret
      set_fact:
        aws_secret_key: "{{ aws_secret_key_prompt.user_input }}"
      when: aws_secret_key is not defined

    - name: get consul key
      pause:
        prompt: "CONSUL KEY, ex: zSni4XjggpO8jW2nofP9VA== please don't use and open README to store encrypted"
      register: consul_key_prompt
      no_log: yes
      when: consul_key is not defined

    - name: set consul key
      set_fact:
        aws_secret_key: "{{ consul_key_prompt.user_input }}"
      when: consul_key is not defined

  roles:
   - { role: aws/cluster, tags: [ 'aws/cluster' ]}