---
########################################################################################################################
#
# Create Cluster
# Documentation: https://docs.ansible.com/ansible/latest/modules/ecs_cluster_module.html
#
########################################################################################################################

    - name: "{{ state }} cluster"
      ecs_cluster:
        state: "{{ state }}"
        name: "{{ ec2_name_prefix }}-cluster"
        delay: 10
        repeat: 10
        region: "{{ ec2_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: cluster