---
########################################################################################################################
#
# Create Cluster
# Documentation: https://docs.ansible.com/ansible/latest/modules/ecs_cluster_module.html
#
########################################################################################################################

    - name: prepare R53 routing
      ecs_service_facts:
        state: "{{ state }}"
        cluster: "foo-bar-consul-cluster"
        service: "foo-bar-consul-service-eu-west-1a"
        details: true
        region: "{{ ec2_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: service
